### ISSUE TITLE
App Crashing when launching iOS - 10.11.0

### ISSUE THREAD

**Issue by sangeethkumarv** [Instabug/Instabug-React-Native#679]
0x000000010261c000 + 2557140
SIGABRT: Attempt to insert non-property list object { "adb_customizations" = 0; "android_build_optimization" = 1; announcements = 1; apm = { "crash_detection_enabled" = 1; "debug_mode_enabled" = 1; "disabled_android_sdk_versions" = ( ); "disabled_ios_sdk_versions" = ( ); enabled = 1; launches = { enabled = 1; "end_api_enabled" = 1; hot = { enabled = 1; "end_api_enabled" = 1; "limit_per_request" = 1000; "store_limit" = 5000; }; "ios_stages_breakdown_enabled" = 0; "limit_per_request" = 1000; "store_limit" = 5000; }; network = { enabled = 1; "graphql_enabled" = 1; "grpc_enabled" = 1; "limit_per_request" = 1000; "store_attributes_limit" = 5; "store_limit" = 5000; }; "sync_interval" = 10; traces = { enabled = 1; "limit_per_request" = 1000; "store_attributes_limit" = 5; "store_limit" = 5000; }; ui = { enabled = 1; "large_drop_duration_mus" = 250000; "limit_per_request" = 1000; "screen_loading" = { enabled = 1; "end_api_enabled" = 1; }; "small_drop_duration_mus" = 16700; "store_limit" = 5000; }; }; "asc_background_render" = 0; "be_user_attributes" = 0; "console_log" = 1; "crash_reporting" = 1; crashes = { anr = 1; cpp = { "disabled_ios_sdk_versions" = ( "10.5.0", "10.5.1", "10.5.2", "10.7.0", "10.7.1", "10.7.3", "10.7.4", "10.7.5", "10.8.0", "10.8.1", "10.8.2", "10.8.3", "10.8.4", "10.8.5", "10.8.6", "10.8.7", "10.8.8", "10.8.9", "10.8.10", "10.9.0", "10.9.1", "10.9.2", "10.9.3", "10.9.4", "10.9.5", "10.9.6", "10.9.7", "10.9.8", "10.9.9", "10.9.10", "10.10.0", "10.10.1", "10.10.2", "10.10.3", "10.10.4", "10.10.5", "10.10.6", "10.10.7", "10.10.8", "10.10.9", "10.11.0", "10.11.1", "10.11.2", "10.11.3", "10.11.4", "10.11.5", "10.11.6", "10.11.7", "10.11.8", "10.11.9", "10.12.0", "10.12.1", "10.12.2", "10.12.3", "10.12.4", "10.12.5", "10.12.6", "10.12.7", "10.12.8", "10.12.9" ); enabled = 0; }; "fatal_hangs" = { enabled = 0; "launch_sensitivity" = 5000; sensitivity = 3000; "watchdog_enabled" = 0; }; "ios_crash_annotations" = 1; oom = 1; }; "crashes_custom_identified_email" = 0; diagnostics = { "non_fatals" = { blacklist = "<null>"; enabled = "0.01"; "non_fatals_max_count" = 10; "occurrences_max_count" = 5; }; "sync_interval" = 1440; }; "disclaimer_text" = 0; "experimental_prompt_fr" = 1; "feature_requests" = 1; "ibg_log" = 1; "ibg_logs_post_crash" = 0; "in_app_messaging" = 1; "instabug_debug_log" = 0; "is_active" = 1; "multiple_attachments" = 1; "network_log" = 1; "new_swizzle2" = 1; "non_translucent_bars_guard_disabled" = 0; "production_usage_detection" = 1; "push_notifications" = 0; "report_phone_number" = 0; "repro_render_context" = 0; "repro_steps" = 1; "repro_steps_screenshots_v2" = 0; "repro_steps_screenshots_v3" = 0; "sdk_log" = { emails = { }; level = 0; "retention_days" = 7; "size_limit" = 20000; "upload_interval" = 43200; uuids = { }; }; sessions = { interval = 720; "max_number" = 10; mode = 2; "sdk_stitching_enabled" = 1; "sdk_stitching_session_timeout" = 1800; }; "sessions_profiler" = 0; surveys = 1; ttl = 0; "user_data" = 1; "user_events" = 1; "user_steps" = 1; "users_keys" = 1; "view_hierarchy" = 0; "view_hierarchy_v2" = 0; "vp_customizations" = 0; "white_label" = 0; } for key **IBGFeaturesLatestFeaturesResponse**

**Comment by nalint2s** [comment]
We are facing same crash in older version of iOS too. Team please update with the fix as many user are affected

**Comment by dltmd6262** [comment]
Also seeing the same crashes here. This is crashing all of our ios users

**Comment by VrajSolanki** [comment]
leading to crash across all the users

**Comment by sangeethkumarv** [comment]
We have reached 100 affected users and 450+ crashes

**Comment by sangeethkumarv** [comment]
<img width="370" alt="Screenshot 2022-03-15 at 6 05 05 PM" src="https://user-images.githubusercontent.com/42767283/158379343-05cbced3-5aea-473b-aa44-930b7bde98e7.png">

**Comment by somsin** [comment]
app getting same issue , Instabug-React-Native team is possible to revert your changes ,  any other solution or live app getting impacted

**Comment by HeshamMegid** [comment]
The issue has been fixed from our side. It may take a few minutes for the configuration that caused this to propagate. There’s no action needed from your side.

**Comment by VrajSolanki** [comment]
@HeshamMegid yes can see the fix  and its working fine. many thanks

**Comment by sangeethkumarv** [comment]
Working as expected, Closing this ticket. Thanks for the support

**Comment by Brma1048** [comment]
@HeshamMegid Thanks for the quick fix but is the problem really fixed? Because yesterday we had this crash over 3000 times and today still 23 times. So it has gotten better, but there are still some crashes.

**Comment by jacquesdev** [comment]
We are also still experiencing this for a couple of our users, please re-open and confirm

**Comment by AliAbdelfattah** [comment]
@Brma1048 @jacquesdev it’s common that you might still be receiving a few crashes, these are most probably cached since the incident yesterday because crashes are sent on the next app launch.
